version: "3.8"
services:
  db:
    image: postgres:14.2-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: prueba

  admin:
    image: adminer
    ports:
      - 8081:8080
